package P3;

/**
* P3/infoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Tuesday, March 31, 2015 2:36:44 PM CDT
*/

public final class infoHolder implements org.omg.CORBA.portable.Streamable
{
  public P3.info value = null;

  public infoHolder ()
  {
  }

  public infoHolder (P3.info initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = P3.infoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    P3.infoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return P3.infoHelper.type ();
  }

}
