package P3;


/**
* P3/infoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Tuesday, March 31, 2015 2:36:44 PM CDT
*/

abstract public class infoHelper
{
  private static String  _id = "IDL:P3/info:1.0";

  public static void insert (org.omg.CORBA.Any a, P3.info that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static P3.info extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (P3.infoHelper.id (), "info");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static P3.info read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_infoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, P3.info value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static P3.info narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof P3.info)
      return (P3.info)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      P3._infoStub stub = new P3._infoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static P3.info unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof P3.info)
      return (P3.info)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      P3._infoStub stub = new P3._infoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
