package P3;


/**
* P3/info.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Tuesday, March 31, 2015 2:36:44 PM CDT
*/

public interface info extends infoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface info
