/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATA_H_RPCGEN
#define _DATA_H_RPCGEN

#include <rpc/rpc.h>


#define DATA_PROG 1
#define DATA_VERS 1
#define DATA 1
extern  char ** data_1();
extern int data_prog_1_freeresult ();

#endif /* !_DATA_H_RPCGEN */
