            module P3{ 
                interface info{ 
                        void view_item(in string username, out string c); 
                        void sell(in string username, in string itemname,in long price, out string c);
                        void bid(in string username, in long price, out string c);
                        void view_high_bidder(in string username,out string name, out string c);
                        void done(in string username, out string output);
                }; 
        }; 